### ISSUE TITLE
ContentType matching query does not exist.

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#132]
Embed Widget genera errores 500 en el servidor 
(no visible para el usuario, solo para el Admin)

_DoesNotExist: ContentType matching query does not exist._
**/media_widget/embed/new/None,**
'HTTP_REFERER': 'https://radiox.org/media_widget/embed/new/picture'

Traceback (most recent call last):

    File "/opt/development_workenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

    File "/opt/development_workenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)

    File "/opt/cyclope_dev/cyclope/apps/media_widget/views.py", line 269, in embed_new
    media_list = _fetch_selection_from_library(media_type)
    
    DoesNotExist: ContentType matching query does not exist.

    File "/opt/cyclope_dev/cyclope/apps/media_widget/views.py", line 401, in _fetch_selection_from_library
    media_list = ContentType.objects.get(model=media_type).get_all_objects_for_this_type().order_by('-creation_date')

    File "/opt/development_workenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)

    File "/opt/development_workenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get % self.model._meta.object_name)

**Comment by Radhi13** [comment]
sqdacafa
